### ISSUE TITLE
유저 스토리 작성

### ISSUE THREAD

**Issue by kkirico** [flagtags/nemonemo#1]
### 로그인 사용자
- 사용자가 로직 리스트를 본다.
  - 사용자가 로직 리스트를 filter 해서 본다.
  
#### 제작자
- 로직 제작
  - 로직
  - 제목
  - 사이즈
  - 제한시간: Date | null
- 내가 제작한 로직 목록 제공

#### 도전자
- 로직 문제 화면 제공
  - 정보(제목, 저자, 제한시간, 사이즈, 힌트행과 힌트열)를 확인할 수 있다.
  - 좋아요를 누를 수 있다.
  - 비어있는 로직영역을 확인할 수 있다.
  - 셀클릭
  - 힌트 숫자 클릭
  - 타이머의 시간이 늘어난다.
  - 자동으로 정답이 확인된다. 
  - 중도 저장
  - 정답 맞춘 로직은 저장하기

#### 관리자
- 전체 사용자 목록을 조회할 수 있다.
  - 정지시킨 사용자 목록을 확인 할 수 있다.
- 사용자 밴
- 문제 삭제
- 문제 제한시간 수정

### 비로그인 사용자
- 사용자는 회원가입을 한다.
  - req: nickname, email, password
  - 이메일 발송
  - email confirmation
  - 사용자 confirm 상태를 바꿔준다.(db)
- 사용자가 로그인한다.
  - req: email, password
  - validation token 생성 
  - 쿠키에 저장
#### 비 로그인 도전자
- 로직 문제 화면 제공
  - 정보(제목, 저자, 제한시간, 사이즈, 힌트행과 힌트열)를 확인할 수 있다.
  - 비어있는 로직영역을 확인할 수 있다.
  - 셀클릭
  - 힌트 숫자 클릭
  - 타이머의 시간이 늘어난다.
  - 자동으로 정답이 확인된다.

**Comment by j03y14** [comment]
스팩정리 이슈로 통합
