### ISSUE TITLE
entity

### ISSUE THREAD

**Issue by kkirico** [flagtags/nemonemo#2]
## entity
- 로직
  - id
  - 답안지
  - 힌트행, 힌트열
  - 제한시간
  - 타이틀
  - 저자
  - 사이즈
- 로직 정보
  - 로직 id
  - 조회 수
  - 완성 수
  - 난이도
  - 따봉
  - 평균기록
  - 최고기록
- 답안지
  - 로직 id
  - 행,열
  - 시간 기록
  - 사용자 id
- 사용자
  - id
  - 닉네임
  - 비밀번호
  - 밴 여부
- 기록
  - 사용자 id
  - 해결한 로직 id
  - 해결에 걸린 시간
- 게임
  - 사용자 id
  - 로직 id
  - 남은시간

**Comment by j03y14** [comment]
스팩 정리 이슈로 통합
